version: 2

base_image: &base_image
  image: circleci/node:8.9.4

job_common: &job_common
  docker:
    - <<: *base_image

restore: &restore
  restore_cache:
    key: code-{{ .Revision }}

store_artifacts: &store_artifacts
  store_artifacts:
    path: output
    destination: /

store_test_results: &store_test_results
  store_test_results:
    path: output

jobs:
  build:
    <<: *job_common
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - deps-{{ checksum "package.json" }}-
            - deps-
      - run: yarn install --frozen-lockfile
      - run: ./node_modules/.bin/greenkeeper-lockfile-update
      - save_cache:
          key: deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run compile
      - save_cache:
          key: code-{{ .Revision }}
          paths:
            - .

  test-style:
    <<: *job_common
    steps:
      - <<: *restore
      - run: yarn run test-style
      - <<: *store_artifacts

  test-unit:
    <<: *job_common
    steps:
      - <<: *restore
      - run: ls -R src test
      - run: yarn run test-unit-coverage
      - <<: *store_artifacts
      - <<: *store_test_results

  greenkeeper:
    <<: *job_common
    steps:
      - <<: *restore
      - run: ./node_modules/.bin/greenkeeper-lockfile-upload

  release:
    <<: *job_common
    steps:
      - <<: *restore
      - run: mkdir -p ~/.ssh
      - run: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: yarn config set registry https://registry.npmjs.org/
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: git config --global user.email "donvoy@convoy.com"
      - run: git config --global user.name "Don Voy"
      - run: yarn run release
      - <<: *store_artifacts

workflows:
  version: 2
  build-test-release:
    jobs:
      - build
      - test-style:
          requires:
            - build
      - test-unit:
          requires:
            - build
      - greenkeeper:
          requires:
            - test-style
            - test-unit
      - release:
          requires:
            - test-style
            - test-unit
          filters:
            branches:
              only:
                - master
                - /v\d+\.\d+/
